### ISSUE TITLE
client.open() failure due to wrong package dependencies.

### ISSUE THREAD

**Issue by VashurkinAnton** [TorchlightSoftware/mongo-watch#17]
Right now dependence "mongodb" used as "*". And because of this when mongodb was release v3.x with breaking API changes, this programm going not work. And we have next eror:
```
TypeError: client.open is not a function
    at module.exports (path-to-project/node_modules/mongo-watch/lib/connect.coffee:22:10)
    at module.exports (path-to-project/node_modules/mongo-watch/lib/getOplogStream.coffee:5:3)
    at new MongoWatch (path-to-project/node_modules/mongo-watch/lib/main.coffee:34:5)
    at Object.<anonymous> (path-to-project/lib/db.js:408:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (path-to-project/api-server.js:17:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

**Comment by sdetweil** [comment]
could u change the title to include info on the client.open() failure.. that way it might appear in a search..

i came to the same solution on my own after 2 days...
