### ISSUE TITLE
Unable to require('mongo-watch')

### ISSUE THREAD

**Issue by gdude2002** [TorchlightSoftware/mongo-watch#4]
Hey,

I've been trying to use this module for a couple weeks to watch the oplog of a Mongo DB. However, yesterday, I noticed the following error..

```
module.js:340
    throw err;
          ^
Error: Cannot find module './lib/main'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/git/[REDACTED]/node_modules/mongo-watch/index.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/git/[REDACTED]/app/routes/socket-watcher.js:26:19)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /root/git/[REDACTED]/server.js:70:38
  at Array.forEach (native)
  at walk_routes (/root/git/[REDACTED]/server.js:64:26)
  at Object.<anonymous> (/root/git/[REDACTED]/server.js:78:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

The line that is failing on is as follows

``` javascript
var mongo_watch = require('mongo-watch');
```

So, clearly, Node isn't able to find lib/main - even though it's clearly right there, in lib/main.coffee.

Any ideas on this?

**Comment by bitmage** [comment]
Eh, I don't think it's related to the mongo-watch library.  The failure might indicate that coffee-script didn't load properly - that would cause the .coffee extension to not be registered and therefore it wouldn't find the file.  I would try:

``` bash
rm -rf node_modules
npm cache clean
npm install
```

This would fix any problems if modules are incorrect for your current node version, or dependencies are broken in some other way.  If that doesn't work let me know.

**Comment by gdude2002** [comment]
It didn't change anything, unfortunately.

Yeah, I don't think this is specific to your code or anything, I just don't really know where to go from here. Honestly, any ideas would be appreciated.

**Comment by jnatherley** [comment]
Currently suffering with the same issue:

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/main'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (******/node_modules/mongo-watch/index.js:2:18)

**Comment by gdude2002** [comment]
I've noticed this issue on Ubuntu 12.10, Ubuntu 13.10 and Windows 8.1 (All 64-bit).

It doesn't seem to affect everyone, but it sure affects all of my machines.

**Comment by bitmage** [comment]
@zol found the issue:

https://github.com/TorchlightSoftware/mongo-watch/pull/6

I've pushed a new version (0.2.2) that is compatible with CoffeeScript >1.7.0.  I also updated the coffee-script dependency in package.json.  This should resolve the issue.

**Comment by gdude2002** [comment]
Yep, this fixed it. Thanks.
